name: CI

on: [push, pull_request]

jobs:
  lint-markdown:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v1

    - name: Setup Node.js
      uses: actions/setup-node@v1

    - name: Install awesome-lint
      run: npm install --global https://github.com/gbdev/list-linter

    - name: Run awesome-lint
      run: awesome-lint
